### PR TITLE
DOC: add note about not removing version specs for old Python versions

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
@astrofrog this is actually a fairly dangerous thing for packages relying on this one. Perhaps they should guard against it by depending on a fixed version of this meta-package - but that of course defeats the purpose of "you don't have to update your `pyproject.toml` anymore.

**Comment by pv** [comment]
If the package description is indeed "the oldest Numpy version that supports the given Python version and platform", then that is immutable information (maybe modulo the micro bugfix release number). I guess it would be sufficient to just clearly describe the rules that apply to updating the information in this package?

**Comment by rgommers** [comment]
> If the package description is indeed "the oldest Numpy version that supports the given Python version and platform", then that is immutable information (maybe modulo the micro bugfix release number).

Ah, good point. That's not how I had understood the intent. I was thinking NEP 29 (as I added in my other PR). Having a `setup_requires` older than `install_requires` isn't necessarily a problem, but would be a bit weird.

**Comment by pv** [comment]
Yes, it's probably good to first be clear what is the aim of this repository.

To me it seems NEP 29 is not exactly relevant for the ABI compatibility issue it is trying to address --- indeed the current setup.cfg here does not follow it. In the language of NEP 29, that in practice increases the Numpy version support from 24 months to ~ the longer period of Python version support. (There's a detailed question here that when a new Python version comes out, what will be selected as the pinned Numpy version, if an older Numpy version already supports it?)

If the data in this repository is not immutable in the above sense (which will be the case if it wants to track NEP 29 more closely), I think projects using this repository will probably have to pin the version at least in the release branch.

**Comment by astrofrog** [comment]
When I created this meta-package I did not intend for this to map onto NEP 29 closely. This is because most packages I've encountered can actually be **built** with older Numpy versions than they support at runtime, so that even if a package tracks NEP 29, it could still use this meta-package and build with older Numpy version, so I didn't see a NEP 29-tracking version as necessary.

My intent was that when a new Python version is released, we update this to specify the oldest Numpy version for which a wheel is available for that Python version. However, we never change the older Python versions. It might be that older Numpy versions actually work fine with the new Python version, but I think it would not be acceptable for most packages to have to build Numpy from source repeatedly whenever pip is called. So really to be pedantic this could be better named as 'oldest-numpy-wheel' if we stay with my original goal.

Having said all this, one could also potentially envisage having a NEP 29-tracking meta-package if needed, but it could be a separate package?

**Comment by rgommers** [comment]
Okay, I think the "oldest wheel" concept makes sense, happy to go with that (and no NEP-29 meta-package). There's not much new C API functionality in NumPy that packages will need, so doing it this way will be fine.

**Comment by rgommers** [comment]
I think the note in this PR is still correct and can be merged as is.

**Comment by astrofrog** [comment]
@rgommers @pv - do we want to consider renaming the package to e.g. ``oldest-numpy-wheel`` or something like that to clarify the intent of the package? Or shall we leave as-is?

**Comment by rgommers** [comment]
Given that this also supports platforms for which we don't have wheels (ppcle64, arm64, s390x, AIX, etc.), I'm happy with the current name. Not a strong opinion though, either way works.

**Pull request merged**
