### PR TITLE
Add loongarch64 support

### PR DESCRIPTION
**Pull request by cheungxi**

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @cheungxi. Could you add some context for those of us not familiar with this architecture? I browsed the wiki page and see there's a Debian port in progress. On Python I only see https://bugs.python.org/issue46498, which is still open. I don't think there's such an architecture in CPython's master branch, is there? How do users get to see this?

**Comment by cheungxi** [comment]
I'm sorry I didn't give a brief introduction to Loongarch ISA. You can get document form this[ link](https://loongson.github.io/LoongArch-Documentation/README-EN.html) . And some common FAQs from[ this](https://blog.xen0n.name/en/posts/tinkering/loongarch-faq/).
As far as I know, Numpy already supports loongarch from [v.122.0](https://github.com/numpy/numpy/releases/tag/v1.22.0) & related[ PR](https://github.com/numpy/numpy/pull/19527).

Thanks

**Review by rgommers — APPROVED** [review]
Thanks @cheungxi. This LGTM. I've added a test for `loongarch64`. In it goes.

**Comment by rgommers** [comment]
New release (`2022.3.27`) is up on PyPI.

**Pull request merged**
