### PR TITLE
fix: header issue with Python 3.10 and macOS

### PR DESCRIPTION
**Pull request by henryiii**

### CODE REVIEW

**Review by tupui — APPROVED** [review]
LGTM it makes sense to update, thanks!

**Comment by henryiii** [comment]
Does a new version need to be made, then, for this to be used?

**Comment by rgommers** [comment]
@tupui please don't be too quick with this repo. I'm testing right now, because this might do the wrong thing on platforms where 1.21.3 is not broken. Verifying whether building against 1.21.4 and then running against 1.21.3 triggers the NumPy version checks on import or not.

**Comment by rgommers** [comment]
> Does a new version need to be made, then, for this to be used?

Yes indeed.

**Comment by tupui** [comment]
Oh ok sorry 🙇

**Comment by henryiii** [comment]
https://github.com/numpy/numpy/blob/5e849108703ae272fb1a3c03c271789c39e68576/numpy/core/setup_common.py#L46

Should be safe.

**Comment by henryiii** [comment]
(Followed this down on my phone based on the version check message; on vacation this week and in a hospital room with my daughter, so can't do an actual check other than of source)

**Comment by rgommers** [comment]
Yes, it's safe in this case. `C_API_VERSION` is the same for all 1.20.x and 1.21.x releases. It's in general still not 100% safe to use an older NumPy version at runtime than at build-time, because the version may not have been incremented correctly (there certainly were C API changes in some bugfix releases around `1.17.5`, `1.18.5` without the C API version having been touched) - but in a bugfix release it's easy to look through the patches and see that there's no problem.

```
cd ../numpy
git clean -xdf
export PYTHONPATH=~/code/numpy
git co v1.21.4
python setup.py build_ext -i

cd ../pywt  # package using the numpy C API
git clean -xdf
python setup.py build_clib
python setup.py build_ext -i
python -c "import pywt as s; s.test()"
python -c "import numpy as np; print(np.__version__)"  # sanity check

cd ../numpy
git co v1.21.3
git clean -xdf
python setup.py build_ext -i
cd ../pywt
python -c "import numpy as np; print(np.__version__)"
python -c "import pywt as s; s.test()"
# (tests pass)

cd ../numpy
git clean -xdf
git co v1.20.3
python setup.py build_ext -i
cd ../pywt
python -c "import numpy as np; print(np.__version__)"
python -c "import pywt as s; s.test()"
# (tests pass - I'd not trust that there was really no C API break here)

cd ../numpy
git clean -xdf
git co v1.17.3
python setup.py build_ext -i
cd ../pywt
python -c "import numpy as np; print(np.__version__)"
python -c "import pywt as s; s.test()"
# Triggers a check:
```

```
$ python -c "import pywt as s; s.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rgommers/code/pywt/pywt/__init__.py", line 15, in <module>
    from ._extensions._pywt import *
  File "pywt/_extensions/_pywt.pyx", line 1, in init pywt._extensions._pywt
    # Copyright (c) 2006-2012 Filip Wasilewski <http://en.ig.ma/>
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
That check comes from Cython in this case. It should be possible to trigger one of the NumPy checks in a package that does not use Cython but does use the NumPy C API directly.

**Comment by rgommers** [comment]
> (Followed this down on my phone based on the version check message; on vacation this week and in a hospital room with my daughter, so can't do an actual check other than of source)

Hope that's nothing too serious. Thanks for the help @henryiii

**Comment by rgommers** [comment]
`0.12` release done

**Comment by tupui** [comment]
Ok so when there is a release, this is the kind of test to do? Should/can we have a CI or something to do this for us instead??

**Comment by rgommers** [comment]
Not when there's a release, only when we do something unusual that deviates from the design. Like here, breaking the rule of pointing to the oldest NumPy release for which wheels are available.

**Pull request merged**
