### PR TITLE
fix: support Windows 32-bit cross-compiles

### LINKED ISSUE #45: No 1.21.4 wheel available for cp310-win32
numpy 1.22.3 is the first release on pypi to have binary wheels for cpython 3.10 on win32, but setup.cfg says to use 1.21.4

https://github.com/scipy/oldest-supported-numpy/blob/8f36bbf7648f6360084212e425816e2c78433973/setup.cfg#L56

### PR DESCRIPTION
**Pull request by henryiii**
Closes #45. Not sure if there's any extra testing that's needed, but I think this should resolve the issue.

### CODE REVIEW

**Comment by matham** [comment]
Yes, can you please remove this exclusion: https://github.com/scipy/oldest-supported-numpy/blob/92de71c78cea5d9836dae3f842f914eb129b6866/.github/workflows/main.yml#L32 so x86 is tested as well now?

**Comment by henryiii** [comment]
Sure, removed.

**Comment by rgommers** [comment]
Thanks a lot @henryiii and @matham!

**Comment by rgommers** [comment]
`2022.4.18` is up on PyPI

**Pull request merged**
